[user]
email = "tfordy63@gmail.com"
name = "fordtom"

[ui]
default-command = "log"
editor = "nvim"

[templates]
git_push_bookmark = '"fordtom/" ++ change_id.short()'

[aliases]
pub = ["git", "push", "-c", "@"]
bump = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "@"]
drop = ["abandon", "--restore-descendants"]
rt = ["rebase", "-d", "trunk()"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

